# Generated by Django 3.1.5 on 2021-01-16 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='admin@local.host', max_length=254),
            preserve_default=False,
        ),
    ]
